BEGIN TRANSACTION;
DROP TABLE IF EXISTS "user";
CREATE TABLE "user" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "username" VARCHAR NOT NULL  UNIQUE , "password" VARCHAR NOT NULL );
INSERT INTO "user" VALUES(1,'leylos16','koikoi');
INSERT INTO "user" VALUES(2,'loulf','ouo');
COMMIT;
